version: '3.3'

services:
  epcis-hash-generator:
    build: .
    image: epcis_event_hash_generator:latest
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    #volumes:
    #  - .:/usr/src/app
    environment:
      - NODE_ENV=production
      - SERVER_PORT=${SERVER_PORT}
      - DEFAULT_HASH_ALGORITHM=${DEFAULT_HASH_ALGORITHM}